# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'importPhotos.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(572, 475)
        self.deleteButton = QtWidgets.QPushButton(Dialog)
        self.deleteButton.setGeometry(QtCore.QRect(30, 260, 127, 25))
        self.deleteButton.setObjectName("deleteButton")
        self.projectErrorLabel = QtWidgets.QLabel(Dialog)
        self.projectErrorLabel.setGeometry(QtCore.QRect(160, 70, 241, 31))
        self.projectErrorLabel.setFrameShape(QtWidgets.QFrame.Panel)
        self.projectErrorLabel.setText("")
        self.projectErrorLabel.setObjectName("projectErrorLabel")
        self.importPhotosLabel = QtWidgets.QLabel(Dialog)
        self.importPhotosLabel.setGeometry(QtCore.QRect(280, 140, 241, 31))
        self.importPhotosLabel.setFrameShape(QtWidgets.QFrame.Panel)
        self.importPhotosLabel.setText("")
        self.importPhotosLabel.setObjectName("importPhotosLabel")
        self.deletePhotosLabel = QtWidgets.QLabel(Dialog)
        self.deletePhotosLabel.setGeometry(QtCore.QRect(280, 260, 241, 31))
        self.deletePhotosLabel.setFrameShape(QtWidgets.QFrame.Panel)
        self.deletePhotosLabel.setText("")
        self.deletePhotosLabel.setObjectName("deletePhotosLabel")
        self.layoutWidget = QtWidgets.QWidget(Dialog)
        self.layoutWidget.setGeometry(QtCore.QRect(110, 10, 345, 54))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setFrameShape(QtWidgets.QFrame.Box)
        self.label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label.setWordWrap(False)
        self.label.setObjectName("label")
        self.horizontalLayout_4.addWidget(self.label)
        self.nameEdit = QtWidgets.QLineEdit(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.nameEdit.sizePolicy().hasHeightForWidth())
        self.nameEdit.setSizePolicy(sizePolicy)
        self.nameEdit.setText("")
        self.nameEdit.setObjectName("nameEdit")
        self.horizontalLayout_4.addWidget(self.nameEdit)
        self.changeName = QtWidgets.QPushButton(self.layoutWidget)
        self.changeName.setObjectName("changeName")
        self.horizontalLayout_4.addWidget(self.changeName)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.currentNameLabel = QtWidgets.QLabel(self.layoutWidget)
        self.currentNameLabel.setObjectName("currentNameLabel")
        self.horizontalLayout.addWidget(self.currentNameLabel)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.layoutWidget1 = QtWidgets.QWidget(Dialog)
        self.layoutWidget1.setGeometry(QtCore.QRect(30, 110, 472, 29))
        self.layoutWidget1.setMaximumSize(QtCore.QSize(472, 16777215))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.cameraProgressBarImport = QtWidgets.QProgressBar(self.layoutWidget1)
        self.cameraProgressBarImport.setMaximumSize(QtCore.QSize(95, 16777215))
        self.cameraProgressBarImport.setProperty("value", 0)
        self.cameraProgressBarImport.setInvertedAppearance(False)
        self.cameraProgressBarImport.setObjectName("cameraProgressBarImport")
        self.horizontalLayout_3.addWidget(self.cameraProgressBarImport)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_3.setMaximumSize(QtCore.QSize(143, 16777215))
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.horizontalLayout_8.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.fileProgressBarImport = QtWidgets.QProgressBar(self.layoutWidget1)
        self.fileProgressBarImport.setMaximumSize(QtCore.QSize(95, 16777215))
        self.fileProgressBarImport.setProperty("value", 0)
        self.fileProgressBarImport.setInvertedAppearance(False)
        self.fileProgressBarImport.setObjectName("fileProgressBarImport")
        self.horizontalLayout_2.addWidget(self.fileProgressBarImport)
        self.label_4 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_4.setMaximumSize(QtCore.QSize(115, 16777215))
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_2.addWidget(self.label_4)
        self.horizontalLayout_8.addLayout(self.horizontalLayout_2)
        self.layoutWidget2 = QtWidgets.QWidget(Dialog)
        self.layoutWidget2.setGeometry(QtCore.QRect(30, 230, 471, 29))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.layoutWidget2)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.cameraProgressBarDelete = QtWidgets.QProgressBar(self.layoutWidget2)
        self.cameraProgressBarDelete.setMaximumSize(QtCore.QSize(95, 16777215))
        self.cameraProgressBarDelete.setProperty("value", 0)
        self.cameraProgressBarDelete.setInvertedAppearance(False)
        self.cameraProgressBarDelete.setObjectName("cameraProgressBarDelete")
        self.horizontalLayout_7.addWidget(self.cameraProgressBarDelete)
        self.label_5 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_7.addWidget(self.label_5)
        self.horizontalLayout_9.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.fileProgressBarDelete = QtWidgets.QProgressBar(self.layoutWidget2)
        self.fileProgressBarDelete.setMaximumSize(QtCore.QSize(97, 16777215))
        self.fileProgressBarDelete.setProperty("value", 0)
        self.fileProgressBarDelete.setInvertedAppearance(False)
        self.fileProgressBarDelete.setObjectName("fileProgressBarDelete")
        self.horizontalLayout_6.addWidget(self.fileProgressBarDelete)
        self.label_6 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_6.addWidget(self.label_6)
        self.horizontalLayout_9.addLayout(self.horizontalLayout_6)
        self.createCamFolderCheckbox = QtWidgets.QCheckBox(Dialog)
        self.createCamFolderCheckbox.setGeometry(QtCore.QRect(40, 190, 231, 23))
        self.createCamFolderCheckbox.setAutoFillBackground(True)
        self.createCamFolderCheckbox.setChecked(True)
        self.createCamFolderCheckbox.setObjectName("createCamFolderCheckbox")
        self.importButton = QtWidgets.QPushButton(Dialog)
        self.importButton.setGeometry(QtCore.QRect(33, 142, 128, 25))
        self.importButton.setObjectName("importButton")
        self.deleteImagesCheckbox = QtWidgets.QCheckBox(Dialog)
        self.deleteImagesCheckbox.setGeometry(QtCore.QRect(40, 170, 212, 23))
        self.deleteImagesCheckbox.setAutoFillBackground(True)
        self.deleteImagesCheckbox.setChecked(True)
        self.deleteImagesCheckbox.setObjectName("deleteImagesCheckbox")
        self.regexEdit = QtWidgets.QTextEdit(Dialog)
        self.regexEdit.setGeometry(QtCore.QRect(10, 300, 271, 71))
        self.regexEdit.setObjectName("regexEdit")
        self.widget = QtWidgets.QWidget(Dialog)
        self.widget.setGeometry(QtCore.QRect(290, 300, 246, 27))
        self.widget.setObjectName("widget")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.cameraProgressBarRegex = QtWidgets.QProgressBar(self.widget)
        self.cameraProgressBarRegex.setMaximumSize(QtCore.QSize(95, 16777215))
        self.cameraProgressBarRegex.setProperty("value", 0)
        self.cameraProgressBarRegex.setInvertedAppearance(False)
        self.cameraProgressBarRegex.setObjectName("cameraProgressBarRegex")
        self.horizontalLayout_5.addWidget(self.cameraProgressBarRegex)
        self.label_7 = QtWidgets.QLabel(self.widget)
        self.label_7.setMaximumSize(QtCore.QSize(143, 16777215))
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_5.addWidget(self.label_7)
        self.widget1 = QtWidgets.QWidget(Dialog)
        self.widget1.setGeometry(QtCore.QRect(290, 340, 218, 27))
        self.widget1.setObjectName("widget1")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.widget1)
        self.horizontalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.fileProgressBarRegex = QtWidgets.QProgressBar(self.widget1)
        self.fileProgressBarRegex.setMaximumSize(QtCore.QSize(95, 16777215))
        self.fileProgressBarRegex.setProperty("value", 0)
        self.fileProgressBarRegex.setInvertedAppearance(False)
        self.fileProgressBarRegex.setObjectName("fileProgressBarRegex")
        self.horizontalLayout_10.addWidget(self.fileProgressBarRegex)
        self.label_8 = QtWidgets.QLabel(self.widget1)
        self.label_8.setMaximumSize(QtCore.QSize(115, 16777215))
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_10.addWidget(self.label_8)
        self.widget2 = QtWidgets.QWidget(Dialog)
        self.widget2.setGeometry(QtCore.QRect(10, 380, 541, 27))
        self.widget2.setObjectName("widget2")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.widget2)
        self.horizontalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.regexButton = QtWidgets.QPushButton(self.widget2)
        self.regexButton.setObjectName("regexButton")
        self.horizontalLayout_11.addWidget(self.regexButton)
        self.projectRegexErrorLabel = QtWidgets.QLabel(self.widget2)
        self.projectRegexErrorLabel.setFrameShape(QtWidgets.QFrame.Panel)
        self.projectRegexErrorLabel.setText("")
        self.projectRegexErrorLabel.setObjectName("projectRegexErrorLabel")
        self.horizontalLayout_11.addWidget(self.projectRegexErrorLabel)
        self.widget3 = QtWidgets.QWidget(Dialog)
        self.widget3.setGeometry(QtCore.QRect(60, 430, 451, 27))
        self.widget3.setObjectName("widget3")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.widget3)
        self.horizontalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.isoButton = QtWidgets.QPushButton(self.widget3)
        self.isoButton.setObjectName("isoButton")
        self.horizontalLayout_12.addWidget(self.isoButton)
        self.comboBox = QtWidgets.QComboBox(self.widget3)
        self.comboBox.setEditable(False)
        self.comboBox.setMinimumContentsLength(9)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.horizontalLayout_12.addWidget(self.comboBox)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.deleteButton.setText(_translate("Dialog", "Delete All Photos"))
        self.label.setText(_translate("Dialog", "Project Name:"))
        self.changeName.setText(_translate("Dialog", "Apply"))
        self.label_2.setText(_translate("Dialog", "Current Project Name:"))
        self.currentNameLabel.setText(_translate("Dialog", "No Name Chosen"))
        self.label_3.setText(_translate("Dialog", "Camera Progress Bar"))
        self.label_4.setText(_translate("Dialog", "File Progress Bar"))
        self.label_5.setText(_translate("Dialog", "Camera Progress Bar"))
        self.label_6.setText(_translate("Dialog", "File Progress Bar"))
        self.createCamFolderCheckbox.setText(_translate("Dialog", "Create Cam Folders In Import"))
        self.importButton.setText(_translate("Dialog", "Import All Photos"))
        self.deleteImagesCheckbox.setText(_translate("Dialog", "Delete Images After Import"))
        self.label_7.setText(_translate("Dialog", "Camera Progress Bar"))
        self.label_8.setText(_translate("Dialog", "File Progress Bar"))
        self.regexButton.setText(_translate("Dialog", "Regex Import/Delete"))
        self.isoButton.setText(_translate("Dialog", "Apply ISO To All Cameras"))
        self.comboBox.setItemText(0, _translate("Dialog", "100"))
        self.comboBox.setItemText(1, _translate("Dialog", "200"))
        self.comboBox.setItemText(2, _translate("Dialog", "400"))
        self.comboBox.setItemText(3, _translate("Dialog", "800"))
        self.comboBox.setItemText(4, _translate("Dialog", "1600"))
        self.comboBox.setItemText(5, _translate("Dialog", "3200"))
        self.comboBox.setItemText(6, _translate("Dialog", "6400"))
        self.comboBox.setItemText(7, _translate("Dialog", "12800"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

